### ISSUE TITLE
[Bug] Tags not applied properly from playbook

### ISSUE THREAD

**Issue by vicsufer** [idealista/postgresql_role#15]
### Description
When using the role on a playbook and only some tags need to be applied, if using the include_role task, the playbook only run those tasks of the role tagged. For instance:

**playbook**
```yaml
- name: Postgresql configuration
  hosts: postgresql
  serial: 1
  tasks:
    - name: Apply postgresql role
      include_role:
        name: postgresql
      tags: postgresql-config
```
**Command that executes all tasks**
```sh
ansible-playbook main.yml
```

**Command which causes the bug**
```sh
ansible-playbook main.yml --tags postgersql-config
```
With the second command the playbook would run only tasks with the provided tags. That is:
https://github.com/idealista/postgresql_role/blob/8a6568a1365b47af0b16415eff008106a5035c1c/tasks/main.yml#L33-L35

Since this task use `include_tasks` the task runs with the playbook, however as `included_tasks` tells the playbook to run tasks from `config.yml` dynamically if the "included" tasks do not have the proper tags they are not run ex:
https://github.com/idealista/postgresql_role/blob/8a6568a1365b47af0b16415eff008106a5035c1c/tasks/config.yml#L3-L9

There are two potential fixes, the first would be to use `import_tasks` since this tells the playbook to run the "imported" tasks statically, therefore they would be run even if the tags do not match, the other option is to tag every included task with the same tag as the task with the `include_tasks` that "includes" them.

In the example the current workaround requires to have knowledge of the files that are within the role which is not user-friendly.
```yaml
- name: Postgresql configuration
  hosts: postgresql
  serial: 1
  tasks:
    - name: Apply postgresql role
      include_role:
        name: postgresql
        tasks_from: config.yml
```
Thie complexity of this workaround scales if several tags need to be applied.

### Why is this needed?

Help users to run only some parts of the role easier.
